---
# file: roles/deploy/tasks/main.yml
- name: be sure ntp is installed on Centos
  when:
    - ansible_distribution == "CentOS"
  yum:
    name: ntp
    state: installed
  become: true
  tags: ntp

- name: be sure ntp is installed on Ubuntu
  when:
    - ansible_distribution == "Ubuntu"
  apt:
    name: ntp
    state: present
  become: true
  tags: ntp

- name: be sure ntp is configured 
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  become: true
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  when: "'docker_containers' not in group_names"
  service:
    name: ntpd
    state: started
    enabled: yes
    use: ansible_service_mgr
  become: true
  tags: ntp
