---
# file: pundun_download.yml
- name: Download pundun package on Ubuntu 16.04 Systems
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "16.04"
  get_url:
    url: "{{ pundun.download_url_ubuntu_16_04 }}"
    dest: "/var/cache/apt/archives/" 
  become: true
  tags: pundun

- name: Download pundun package on Ubuntu 14.04 Systems
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "14.04"
  get_url:
    url: "{{ pundun.download_url_ubuntu_14_04 }}"
    dest: "/var/cache/apt/archives/" 
  become: true
  tags: pundun

- name: Download pundun package on Centos 7 Systems
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  get_url:
    url: "{{ pundun.download_url_centos_7 }}"
    dest: "/tmp/"
  become: true
  tags: pundun

- name: Download pundun package on Centos 6 Systems
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  get_url:
    url: "{{ pundun.download_url_centos_6 }}"
    dest: "/tmp/"
  become: true
  tags: pundun
